# Generated by Django 6.0 on 2026-02-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30, null=True)),
                ('desg', models.CharField(max_length=30, null=True)),
                ('salary', models.FloatField(null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
